name: test-missing-perms
on: [push]
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: use github token
        env:
          TOK: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $TOK" https://api.github.com/user
